### ISSUE TITLE
error run task or compil

### ISSUE THREAD

**Issue by easyvico** [renaco/gulp-pug-mjml-mailing#1]
Hi, when i run task or compil email  i have errors...of course i did npm i -E
[15:12:40] Working directory changed to ~/Documents/gulp-pug-mjml-mailing
```
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/laurentvicherd/Documents/gulp-pug-mjml-mailing/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/laurentvicherd/Documents/gulp-pug-mjml-mailing/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/laurentvicherd/Documents/gulp-pug-mjml-mailing/gulpfile.js:34:6)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
any idea how to fix it ? thx a lot

**Comment by renaco** [comment]
Hi @easyvico ,

I pushed the fix and changes, please tell me it appears the problem again.

Regards!

**Comment by easyvico** [comment]
Hi @renaco  Thank you very much i can launch the project...just the "npm run watch" doesn't work. What did you do to fix the error ?

**Comment by renaco** [comment]
@easyvico 

I did forget work with the new dependencies after update to Gulp 4. I did send work in progress to master :(

Thanks for you issue! :)

**Comment by easyvico** [comment]
Hi @renaco , i opened a new issue on the mixin compile error...i can’t find why it doesn’t work.
Thx for your help ^^
https://github.com/renaco/gulp-pug-mjml-mailing/issues/2



Le 28 mars 2019 à 20:26, Renán Romero <notifications@github.com<mailto:notifications@github.com>> a écrit :


@easyvico<https://github.com/easyvico>

I did forget work with the new dependencies after update to Gulp 4. I did send work in progress to master :(

Thanks for you issue! :)

**Comment by renaco** [comment]
Hi @easyvico , 
I'm busy these days, I will be reviewing.

Thanks for your comments!!

**Comment by easyvico** [comment]
Hi @renaco<mailto:reply@reply.github.com>

Thank you for reply, i understand, no problem 😉. I tried to figure out what was the problem but i didn't find...
regards



________________________________
De : Renán Romero <notifications@github.com>
Envoyé : mardi 2 avril 2019 16:42
À : renaco/gulp-pug-mjml-mailing
Cc : easyvico; Mention
Objet : Re: [renaco/gulp-pug-mjml-mailing] error run task or compil (#1)


Hi @easyvico<https://github.com/easyvico> ,
I'm busy these days, I will be reviewing.

Thanks for your comments!!
